workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/<project-id>/<docker-img>
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY